function load(package_name)
    arguments
        package_name string {mustBeMember(package_name, ...
            [ ...
            "Connector", ...
            "aDevice", ...
            "Debug_msg", ...
			"Plotlib", ...
			"FRA_tools", ...
            "Common"
            ])}
    end

    load_package(package_name, true);

end