
function [resp, cmd_status] = exec(CMD_str, echo)
arguments
    CMD_str string
    echo logical = false
end

CMD_str = char(CMD_str);

if isunix
    CMD_str = ['export TERM=ansi; ' CMD_str];
end

CMD_str = ['(' CMD_str ')'];

if echo
    disp(['CMD: ' newline char(CMD_str) newline])
    [cmd_status, resp] = system(CMD_str, "-echo");
else
    [cmd_status, resp] = system(CMD_str);
end

if isunix
    resp = stripANSI(resp);
end

if nargout > 1
    no_throw = true;
else
    no_throw = false;
end

if ~no_throw
    if cmd_status ~= 0
        msg = ['CMD execution fails:' newline ...
            '  CMD:' newline ...
            '  ' char(CMD_str)  newline ...
            'Response: ' newline ...
            char(resp)];
        error(msg)
    end
end


end



% -----------------------------------------------------------------------------

% % Example 1: Git output with colors
% raw = '* [32mmaster[m[m';
% 
% % Example 2: ls with colors
% raw2 = 'file.txt[0m  [01;34mdir[0m';
% 
% % Example 3: Complex escape sequences
% raw3 = '[1;31mError[0m: [33mWarning[0m';
% 
% cleaned1 = stripANSI(raw)   % '* master'
% cleaned2 = stripANSI(raw2)  % 'file.txt  dir'
% cleaned3 = stripANSI(raw3)  % 'Error: Warning'



function cleanStr = stripANSI(rawStr)
    % NOTE This function is auto-generated by Deepseek.
    % Remove ALL ANSI escape sequences from a string
    % Handles CSI sequences, OSC sequences, and various control characters
    
    if isempty(rawStr)
        cleanStr = rawStr;
        return;
    end
    
    % Pattern 1: CSI sequences (most common)
    % ESC [ ... m (colors, styles)
    % ESC [ ... K (erase line)
    % ESC [ ... J (erase screen)
    % ESC [ ... A/B/C/D (cursor movement)
    % ESC [ ... n (device status)
    cleanStr = regexprep(rawStr, '\x1B\[[0-9;:]*[a-zA-Z@]', '');
    
    % Pattern 2: OSC sequences (e.g., title bar changes)
    % ESC ] ... BEL or ESC ] ... ESC \
    cleanStr = regexprep(cleanStr, '\x1B\][^\x07\x1B]*(\x07|\x1B\\)', '');
    
    % Pattern 3: Simple escape sequences
    % ESC c (reset), ESC E (newline), ESC M (reverse line feed), etc.
    cleanStr = regexprep(cleanStr, '\x1B[()#%*+ -./]', '');
    
    % Pattern 4: SGR sequences (specifically for colors/styles)
    % Handles \x1B[38;5;...m, \x1B[48;5;...m, etc.
    cleanStr = regexprep(cleanStr, '\x1B\[[0-9;]*m', '');
    
    % Pattern 5: Any remaining ESC character followed by anything
    % This catches any missed sequences
    cleanStr = regexprep(cleanStr, '\x1B[^a-zA-Z]', '');
    cleanStr = regexprep(cleanStr, '\x1B', '');
    
    % Pattern 6: Remove extra whitespace artifacts
    cleanStr = regexprep(cleanStr, '[\x00-\x08\x0B\x0C\x0E-\x1F]', '');
    
    % Pattern 7: Remove trailing whitespace and normalize newlines
    cleanStr = strtrim(cleanStr);
    
    % Remove any leftover backspace characters
    cleanStr = regexprep(cleanStr, '\x08', '');
end
